# Generated by Django 4.0.4 on 2022-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_image'),
        ),
    ]
