# Generated by Django 4.0.4 on 2022-05-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='proccessed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
