# Generated by Django 4.0.4 on 2022-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_proccessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cashback',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
