# Generated by Django 4.0.4 on 2022-05-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
