# Generated by Django 4.0.6 on 2022-08-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('beverages', 'beverages'), ('foods', 'foods'), ('groceries', 'groceries')], default='groceries', max_length=20, null=True),
        ),
    ]
